# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c37af42b47f8b4b0e2ea8308cda0683bcc3657cd44cb68b8c29ebd7587be3e6762a484fb2c2e589f87d1a47378c8acd5af0eb1e2ecae73eb01dfdf901ba922f7

test:
  secret_key_base: b7607d7372437319e206aa26f3d73743b3db590f22866d59832a19daae19a4870d2df02f3fc092b800b9b405a2cb25b6b270186da42099ff0656e83d13d167c4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
